# Generated by Django 4.2 on 2026-03-14 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('food', 'Корм'), ('medicine', 'Лекарства'), ('toys', 'Игрушки'), ('equipment', 'Оборудование'), ('hygiene', 'Гигиена'), ('other', 'Другое')], max_length=20, verbose_name='Категория')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('partially_closed', 'Частично закрыта'), ('closed', 'Закрыта')], default='open', max_length=20, verbose_name='Статус')),
                ('quantity_required', models.PositiveIntegerField(verbose_name='Сколько нужно')),
                ('unit', models.CharField(choices=[('pcs', 'шт.'), ('kg', 'кг'), ('l', 'л'), ('pack', 'уп.')], default='pcs', max_length=10, verbose_name='Единица измерения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Нужда',
                'verbose_name_plural': 'Нужды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='Помощник')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='wishlist.need', verbose_name='Нужда')),
            ],
            options={
                'verbose_name': 'Вклад',
                'verbose_name_plural': 'Вклады',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='need',
            constraint=models.UniqueConstraint(fields=('title', 'created_by'), name='unique_need_per_user'),
        ),
    ]
