# Generated by Django 5.2.12 on 2026-04-03 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('exhibition', 'Выставка'), ('meetup', 'Встреча'), ('adoption', 'День усыновления'), ('vaccination', 'Вакцинация'), ('other', 'Другое')], max_length=20, verbose_name='Категория')),
                ('location', models.CharField(max_length=300, verbose_name='Место')),
                ('event_date', models.DateTimeField(verbose_name='Дата события')),
                ('max_participants', models.PositiveIntegerField(default=0, help_text='0 = без ограничения', verbose_name='Макс. участников')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('ongoing', 'Проходит'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Зарегистрирован'), ('cancelled', 'Отменён')], default='registered', max_length=20, verbose_name='Статус')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Событие')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('title', 'event_date'), name='unique_event_title_date'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('event', 'participant'), name='unique_registration'),
        ),
    ]
